# Generated by Django 5.0.6 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pin_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]

