# Generated by Django 5.0.6 on 2026-01-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_uploadsession"),
        ("share", "0003_emailverificationtoken_pending_credentials"),
    ]

    operations = []
